### ISSUE TITLE
Add option to cancel "Add task" action

### ISSUE THREAD

**Issue by micalevisk** [enotcode/doit#1]
I think it would be a good feature...

Something like
![sample](https://user-images.githubusercontent.com/13461315/34022447-b1614e8c-e115-11e7-95ce-9fc196fa6312.gif)

**Comment by enotcode** [comment]
@micalevisk I'm will fix it.

**Comment by enotcode** [comment]
@micalevisk It's done ✅

**Comment by enotcode** [comment]
P.S. The bot was updated, and moved to @jditbot
